name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit:
    name: unit-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Neovim (0.10.4)
        run: |
            wget https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux64.tar.gz
            tar xzf nvim-linux64.tar.gz
            sudo mv nvim-linux64 /usr/local/nvim
            sudo ln -sf /usr/local/nvim/bin/nvim /usr/bin/nvim
            nvim --version

      - name: Install test dependencies (plenary.nvim)
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim \
            ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim

      - name: Install telescope.nvim dependency
        run: |
          git clone --depth 1 https://github.com/nvim-telescope/telescope.nvim \
            ~/.local/share/nvim/site/pack/vendor/start/telescope.nvim

      - name: Run tests (Plenary/Busted)
        run: |
            nvim --headless -u tests/minimal_init.lua \
            -c "PlenaryBustedDirectory tests --exclude-pattern telescope_integration_spec" +q

